model:
  arch: minigpt_v2
  model_type: pretrain
  max_txt_len: 500
  end_sym: "</s>"
  low_resource: True
  prompt_template: "[INST] {} [/INST]"
  llama_model: "meta-llama/Llama-2-7b-chat-hf"
  ckpt: "./minigpt4/vivqa_outputs/20250314075/checkpoint_1.pth"
  lora_r: 64
  lora_alpha: 16

datasets:
  cc_sbu_align:
    vis_processor:
      train:
        name: "blip2_image_eval"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"

evaluation_datasets:
  vivqa:
    batch_size: 4
    eval_file_path: "./data/ViVQA/test.csv"
    img_path: "./data/ViVQA/images"
    max_new_tokens: 20

run:
  task: image_text_pretrain
  name: minigptv2_evaluation
  save_path: eval_outputs
